#!/bin/bash

name=''
cp=''
src=src

if [ -n "$1" ]&&[ -d "$1" ]
then
 src=$(echo $1 | sed 's%[/\.]*%%g;')
 case ${src} in
 src)
  cp='bin';;
 awt)
  cp='bin';;
 test)
  cp='bin';;
 *)
  cat<<EOF>&2
$0 error unrecognized source '${src}'
EOF
  exit 1
 esac
else
 name='src'
 cp='bin'
fi


2>&1 javac -classpath ${cp} -d bin $(find ${src} -type f -name '*.java') | tee compile.log
