#!/bin/bash

name=''
tgt=fv3-font.jar

if [ -n "$1" ]&&[ -d "$1" ]
then
 name=$(echo $1 | sed 's%[/\.]*%%g;')
 tgt=fv3-font-${name}.jar
else
 name='src'
fi

if [ -d bin ]
then
 cd bin
 2>/dev/null ln -s ../fonts

 case ${name} in
 #
 #
 src)
  if [ ! -d fv3/font ]
  then
   cat<<EOF>&2
$0 error requires initial 'compile'.
EOF
   exit 1
  elif [ -d fv3/font/awt ]
  then
   cat<<EOF>&2
$0 error dirty build target.
EOF
   exit 1
  else
   jar cf ../${tgt} *
  fi ;;
 #
 #
 awt)
  if [ -d fv3/font/test ]
  then
   cat<<EOF>&2
$0 error dirty build target.
EOF
   exit 1
  else
   jar cf ../${tgt} *
  fi ;;
 #
 #
 test)
  if [ ! -d fv3/font/awt ]
  then
   cat<<EOF>&2
$0 error requires 'compile awt'.
EOF
   exit 1
  else
   2>/dev/null mkdir META-INF
   cat<<EOF>META-INF/MANIFEST.MF
Main-Class: fv3.font.test.Main
EOF
   jar cmf META-INF/MANIFEST.MF ../${tgt} * 
  fi ;;
 *)
  cat<<EOF>&2
$0 error unrecognized source '${src}'
EOF
  exit 1
 esac
 cd ..
 ls -l ${tgt}
else
 echo "$0: error requires compile"
 exit 1
fi
